env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
plugins:
  - '@typescript-eslint'
rules: {}
